apiVersion: v1
kind: Pod
metadata:
  name: dacon-pod
  labels:
    app: dacon
spec:
  containers:
  - name: nginx
    image: kubehatesme/dacon-web
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dacon-svc
  labels:
    app: dacon
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: dacon
